"""
The idea behind suritwist is to leverage dnstwist and suricata in order to detect user going to potentially malicious pages.
If you can't run your local copy of dnstwist (https://github.com/elceef/dnstwist), you can go to https://dnstwist.it and 
export the results to a json file.
"""

import argparse
import base64
import json
from pathlib import Path

QUERY_DOMAIN = ""


def read_source_json(filename: str) -> list:
    """
    Reads the source json from disk, removes the original dns query and returns a list of the remaining domains.

    Args:
       filename (str): Filename of the JSON file generated by dnstwist

    Returns:
       list: List with the remaining domain names
    """

    dns_dataset = []

    if isinstance(filename, str):

        if Path(filename).exists():
            if args.verbose:
                print(f"Reading in JSON file {filename}")

            with open(filename, "r") as file:
                json_data = json.load(file)

            for answer in json_data:
                if answer["fuzzer"] != "*original":
                    if args.verbose:
                        print(f"domain {answer['domain']} added to list.")
                    dns_dataset.append(answer["domain"])
                else:
                    global QUERY_DOMAIN
                    QUERY_DOMAIN = answer["domain"]

        else:
            raise ValueError(f"{filename} does not exist.")
    else:
        raise TypeError("filename must be of type string")
    return dns_dataset


def transform_domain_to_base64(dns_dataset: list) -> list:
    """
    Transforms a list of dns names into their base64 equivalent and returns the list.

    Args:
        dns_dataset (list): The list of dns names you whish to transform

    Returns:
        list: List of the base64 domain names
    """
    base64_dataset = []

    if isinstance(dns_dataset, list):
        for dns_name in dns_dataset:

            if args.verbose:
                print(f"Transforming {dns_name} into it's base64 equivalent.")

            base64_dataset.append(base64.b64encode(str(dns_name).encode("utf-8")))

    else:
        raise TypeError("dns_dataset must be of type list")

    return base64_dataset


def write_base64_dataset_to_file(base64_dataset: list, filename: str) -> bool:
    """
    Writes the base64 dataset to disk so it can be leveraged in a suricata rule.

    Args:
        base64_dataset (list): The base64 list of the dns names

    Returns:
        bool: True if the file was successfully written to disk, False otherwise.
    """

    if isinstance(base64_dataset, list):
        if args.verbose:
            print("base64_dataset is of type list")

        try:
            with open(filename, "w+") as file:
                for base64_encoded_dns in base64_dataset:
                    if args.verbose:
                        print(
                            f"adding {base64_encoded_dns.decode(encoding='utf-8')} to {filename}"
                        )
                    file.write(f"{base64_encoded_dns.decode(encoding='utf-8')}\n")
            return True
        except Exception:
            return False

    else:
        raise TypeError("base64_dataset must be of type list")


def main():
    # print(f"query: {QUERY_DOMAIN}")

    dns_dataset = read_source_json(args.inputfile[0])
    base64_dataset = transform_domain_to_base64(dns_dataset=dns_dataset)

    if write_base64_dataset_to_file(
        base64_dataset=base64_dataset, filename=args.outputfile[0]
    ):
        print(f"Your dataset is ready for use at {args.outputfile[0]}\n")
    else:
        print(f"Something went wrong ...")

    if args.rule:
        if args.sid is None:
            sid = 1
        else:
            sid = args.sid[0]

        if args.rev is None:
            rev = 1
        else:
            rev = args.rev[0]

        print("Your rule:\n")
        header = "alert dns $HOME_NET any -> $EXTERNAL_NET any"
        message = f"msg: Potential malicious domain - variation on {QUERY_DOMAIN}."

        print(
            f"{header} ({message};\\\n\tdns.query;dataset:isset, potentially-bad-domains-{QUERY_DOMAIN} , load {args.outputfile[0]}, type string;\\\n\tthreshold:type both, track by_src, count 1, seconds 300;\\\n\tclasstype:bad-unknown;  sid:{sid}; rev:{1})\n"
        )


if __name__ == "__main__":
    argumentparser = argparse.ArgumentParser(
        prog="suritwist", description="Generate your dataset for dnstwist"
    )
    argumentparser.add_argument(
        "inputfile", nargs=1, type=str, help="input file in json format"
    )
    argumentparser.add_argument(
        "outputfile", nargs=1, type=str, help="suricata dataset file"
    )
    argumentparser.add_argument(
        "-e",
        "--exclude",
        nargs="*",
        action="store",
        help="domains you want to exclude from the dataset",
    )
    argumentparser.add_argument("-r", "--rule", action="store_true", help="show rule")
    argumentparser.add_argument(
        "--sid",
        nargs=1,
        type=int,
        help="specify your suricata rule id, default is 100001",
    )
    argumentparser.add_argument(
        "--rev", nargs=1, type=int, help="specify your revision, default is 1"
    )
    argumentparser.add_argument(
        "-v", "--verbose", action="store_true", help="output verbose"
    )
    args = argumentparser.parse_args()
    main()
